### ISSUE TITLE
RXTX not playing nicely with symlinked USB-1Wire adaptors

### ISSUE THREAD

**Issue by marcass** [home-climate-control/dz#18]
Problem: Can't connect DZ3 to the symlinked address assigned in udev rule

Issue causing problem: I have 2 usb devices that must have a consistent port for process to sniff data coming from/going to port

udev rule works great for assigning port:

`ls -l /dev | grep DZ3` 
gives: 
`lrwxrwxrwx  1 root root           7 Mar  5 19:37 DZ3 -> ttyUSB1`

conf file snip:
```
<bean id="device_factory" class="net.sf.dz3.device.sensor.impl.onewire.OwapiDeviceFactory" init-method="start">
                <constructor-arg index="0" value="/dev/DZ3"/>
                <constructor-arg index="1" value="regular"/>
    </bean>
```

Error message:

```
19:41:18,281 ERROR OwapiDeviceFactory pool-3-thread-1 [] Uncaught exception: 
java.lang.IllegalArgumentException: Port '/dev/DZ3' unavailable, valid values: [/dev/ttyUSB1, /dev/ttyUSB2]
```

Is this an upstream problem with rxtx stuff or similar?

I will just poll port in meantime and change config to suit so not a critical issue

marcus

**Comment by climategadgets** [comment]
I'd say that this should rather be fixed in RxTx than in DZ, but in any case it's a gray area. If you ask to recognize symlinks in /dev pointing to valid serial devices, why not then ask to browse the whole filesystem for symlinks to those devices? I'm exaggerating, of course, but I hope you see the point.

Another problem here is that it is very easy to miss the correct device - TTY numbers will only be consistent if you connect the devices in the same order, and/or the physical connections stay the same after reboot, so making a symlink like that is somewhat asking for trouble. Hence, I won't be doing anything on this issue - but let it stay here for the record.

Makes me regret (again) that USB devices with known manufacturer and product IDs and unique serial numbers didn't catch on.

**Comment by marcass** [comment]
Yeah, I agree regarding manufacturers not catching on.

In this situation I don't do the symlinking, udev does. So when the 1-wire adaptor is plugged in udev matches a rule and applies the symlink to point at whichever tty port the adaptor is assigned - was hoping to avoid the annoyance of the random assignment of USB ports on reboot that occasionally gets me trawling logs to see why things aren't working :)

I may take it up with rxtx, and will probably find there are very good reasons for port checking (as you have suggested).

Thanks

Marcus
