### ISSUE TITLE
Configuration guide needs updating.

### ISSUE THREAD

**Issue by jbuszkie** [home-climate-control/dz#24]
http://www.homeclimatecontrol.com/configuration-guide

This needs updating to reflect the newer google calendar API.  The bean template still has the credential information.

**Comment by jbuszkie** [comment]
Along those same lines...  The links to code in that presentation point to some SF code and not github.

**Comment by climategadgets** [comment]
From v4.0.0 onward, the documentation will always be in sync with the code because it is published directly in the branch it is documenting. See the [doc root](https://github.com/home-climate-control/dz/blob/master/docs/index.md) for more details.

Update to the originally submitted URL is on its way.

**Comment by climategadgets** [comment]
https://www.homeclimatecontrol.com/configuration-guide now contains updated set of links. More changes (in particular, related to calendar) are coming - all of them will be now published directly into the Git repo, bye bye bit rot.
